routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\InteractiveController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\BuyController;
use App\Http\Controllers\CourseController as SiteCourseController;
use App\Http\Controllers\LessonController as SiteLessonController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InteractiveController as SiteInteractiveController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('main');
Route::get('set_lang/{lang}', [HomeController::class, 'setLang'])->name('set_lang');
Route::get('course/{course}', [SiteCourseController::class, 'show'])->name('course.show');
Route::get('buy/{course}', [BuyController::class, 'show'])->name('buy.show');
Route::get('admin', [AdminHomeController::class, 'index'])->name('admin');

Route::middleware(['verified'])->group(function () {
    // Роуты закрытые для неверифицированных
    Route::get('lesson/{lesson}', [SiteLessonController::class, 'show'])->name('lesson.show');
    Route::get('lesson/{lesson}/{user?}', [SiteLessonController::class, 'show'])->middleware('admin')->name('lesson.show');
    Route::post('interactive/{lesson}', [SiteInteractiveController::class, 'store'])->name('interactive.store');
    Route::post('interactive/{lesson}/{user?}', [SiteInteractiveController::class, 'store'])->middleware('admin')->name('interactive.store');
    Route::post('buy/{course}', [BuyController::class, 'store'])->name('buy.store');

    Route::middleware(['admin'])->prefix('admin')->group(function () {
        // Роуты открытые только для админа
        Route::get('/', [AdminHomeController::class, 'index'])->name('admin');
        Route::name('admin.')->group(function () {
            // Курсы
            Route::resource('course', CourseController::class);
            Route::resource('course/{course}/lesson', LessonController::class)->only(['create', 'store']);
            Route::get('course/{course}/restore', [CourseController::class, 'restore'])->name('course.restore');
            // Уроки
            Route::resource('lesson', LessonController::class)->only(['edit', 'update', 'destroy']);
            Route::get('lesson/{lesson}/restore', [LessonController::class, 'restore'])->name('lesson.restore');
            // Пользователи
            Route::resource('user', UserController::class)->only(['index', 'edit', 'update']);
            // Интерактив
            Route::get('interactive', [InteractiveController::class, 'index'])->name('interactive.index');
            Route::get('interactive/{lesson}', [InteractiveController::class, 'show'])->name('interactive.show');
            // Загрузчик изображений
            Route::post('image-uploader', [ImageController::class, 'upload'])->name('image-uploader');
        });
    });
});

require __DIR__.'/auth.php';

app/Models/Lesson.php
<?php

namespace App\Models;

use App\Models\Interactive;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

/**
 * Уроки
 *
 * @property int $id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Carbon $deleted_at
 * @property int $lesson_id
 * @property string $name_ru
 * @property string $name_en
 * @property string $name_fr
 * @property float $content_ru
 * @property float $content_en
 * @property float $content_fr
 */
class Lesson extends Model
{
    use HasFactory,
        SoftDeletes;

    protected $table = 'lessons';

    protected $fillable = [
        'number',
        'name_ru',
        'name_en',
        'name_fr',
        'content_ru',
        'content_en',
        'content_fr',
    ];

    protected $appends = [
        'name',
        'content',
        'poster',
        'question_count',
        'new_question_count',
        'has_question',
    ];

    public function getNameAttribute()
    {
        $localeName = 'name_' . app()->getLocale();

        return $this->$localeName;
    }

    public function getContentAttribute()
    {
        $localeContent = 'content_' . app()->getLocale();

        return $this->$localeContent;
    }

    public function getPosterAttribute()
    {
        $filePath = 'images/lessons/' . $this->id . '.jpg';

        if (!Storage::exists($filePath)) {
            return null;
        }

        return $filePath . '?' . time();
    }

    /**
     * Количество вопросов
     *
     * @return int
     */
    public function getQuestionCountAttribute(): int
    {
        return $this->interactives()->count();
    }

    public function getHasQuestionsAttribute()
    {
        return !!$this->new_question_count;
    }

    /**
     * Количество новых вопросов
     *
     * @return int
     */
    public function getNewQuestionCountAttribute(): int
    {
        return $this->interactives()
            ->with('messages', function ($builder) {
                $builder->latest();
            })
            ->get()
            ->filter(function ($interactive) {
                return !in_array($interactive->messages->first()->user_id, config('app.admin_user_ids'));
            })
            ->count();
    }

    /**
     * Курс
     *
     * @return BelongsTo
     */
    public function course(): BelongsTo
    {
        return $this->belongsTo(Course::class);
    }

    /**
     * Сообщения интерактива
     *
     * @return HasMany
     */
    public function interactives(): HasMany
    {
        return $this->hasMany(Interactive::class);
    }
}

app/Http/Controllers/Admin/LessonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\LessonRequest;
use App\Models\Course;
use App\Models\Lesson;
use App\Services\LessonService;
use Artesaos\SEOTools\Facades\SEOMeta;

class LessonController extends Controller
{
    public function create(Course $course)
    {
        SEOMeta::setTitle(__('Add lesson'));

        return view('admin/lesson/form', [
            'course' => $course
        ]);
    }

    public function store(Course $course, LessonRequest $request, LessonService $lessonService)
    {
        $lessonService->create($course, $request);

        return redirect()->route('admin.course.index')->withSuccess(__('Lesson created'));
    }

    public function edit($id)
    {
        SEOMeta::setTitle(__('Edit lesson'));

        $lesson = Lesson::withTrashed()->findOrFail($id);

        return view('admin/lesson/form', [
            'lesson' => $lesson,
        ]);
    }

    public function update(LessonRequest $request, $id, LessonService $lessonService)
    {
        $lesson = Lesson::withTrashed()->findOrFail($id);

        $lessonService->update($lesson, $request);

        return redirect()->route('admin.course.index')->withSuccess(__('Lesson updated'));
    }

    public function destroy($id, LessonService $lessonService)
    {
        $lesson = Lesson::withTrashed()->findOrFail($id);

        $lessonService->delete($lesson);

        session()->flash('success', __('Lesson deleted'));
    }

    public function restore($id, LessonService $lessonService)
    {
        $lesson = Lesson::withTrashed()->findOrFail($id);

        $lessonService->restore($lesson);

        return back()->withSuccess(__('Lesson restored'));
    }
}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lesson;
use App\Models\User;
use App\Services\LessonService;
use Artesaos\SEOTools\Facades\SEOMeta;

class LessonController extends Controller
{
    public function show(LessonService $lessonService, Lesson $lesson, ?User $user = null)
    {
        if (auth()->user()->cant('view', $lesson->course)) {
            return redirect()->route('buy.show', $lesson->course)->withPageinfo(__('To access the lesson, purchase the course'));
        }

        SEOMeta::setTitle($lesson->name . ' | ' . $lesson->course->name);
        SEOMeta::setDescription($lesson->name . '. ' . $lesson->course->name);

        $lessons = $lessonService->getOtherLessons($lesson);

        $interactive = $lessonService->getInteractive($lesson, $user ?? auth()->user());

        return view('lesson', [
            'lesson' => $lesson,
            'lessons' => $lessons,
            'interactive' => $interactive,
            'user' => $user,
        ]);
    }
}

resources/views/admin/lesson/form.blade.php
@extends('layouts/admin')

@section('content')
    <h1>@lang((isset($lesson) ? 'Edit' : 'Add') . ' lesson')</h1>

    @error('*')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
    @enderror

    <form action="{{ isset($lesson) ? route('admin.lesson.update', $lesson) : route('admin.lesson.store', [$course]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @if (isset($lesson))
            @method('PATCH')
        @endif

        <div role="tabpanel clearfix">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs nav-justified" role="tablist">
                <li role="presentation" class="active">
                    <a href="#ru" aria-controls="ru" role="tab" data-toggle="tab">@lang('ru')</a>
                </li>
                <li role="presentation">
                    <a href="#en" aria-controls="en" role="tab" data-toggle="tab">@lang('en')</a>
                </li>
                <li role="presentation">
                    <a href="#fr" aria-controls="fr" role="tab" data-toggle="tab">@lang('fr')</a>
                </li>
            </ul>
            <br>
            <div class="form-group">
                <label for="">@lang('Number')</label>
                <p class="help-block">@lang('This field is used to sort')</p>
                <input type="text" name="number" class="form-control" value="{{ old('number', $lesson->number ?? '') }}">
            </div>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="ru">
                    <div class="form-group">
                        <label for="name_ru">@lang('Title on russian')</label>
                        <input type="text" name="name_ru" class="form-control" value="{{ old('name_ru', $lesson->name_ru ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="content_ru">@lang('Content on russian')</label>
                        <textarea name="content_ru" class="summernote form-control">{{ old('content_ru', $lesson->content_ru ?? '') }}</textarea>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="en">
                    <div class="form-group">
                        <label for="name_en">@lang('Title on english')</label>
                        <input type="text" name="name_en" class="form-control" value="{{ old('name_en', $lesson->name_en ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="content_en">@lang('Content on english')</label>
                        <textarea name="content_en" class="summernote form-control">{{ old('content_en', $lesson->content_en ?? '') }}</textarea>
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="fr">
                    <div class="form-group">
                        <label for="name_fr">@lang('Title on french')</label>
                        <input type="text" name="name_fr" class="form-control" value="{{ old('name_fr', $lesson->name_fr ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="content_fr">@lang('Content on french')</label>
                        <textarea name="content_fr" class="summernote form-control">{{ old('content_fr', $lesson->content_fr ?? '') }}</textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="">@lang('Poster')</label>
            <span class="help-block">@lang('Left empty if you not want to change')</span>
            <input type="file" name="image" accept="image/*">
        </div>
        <div class="form-group">
            <input type="hidden" name="set_watermark" value="0">
            <label for="set_watermark">
                <input type="checkbox" checked name="set_watermark" id="set_watermark" value="1"> @lang('Set watermark on poster')
            </label>
        </div>
        <button type="submit" class="btn btn-primary">@lang('Save')</button>
    </form>

@endsection