routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\InteractiveController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\BuyController;
use App\Http\Controllers\CourseController as SiteCourseController;
use App\Http\Controllers\LessonController as SiteLessonController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InteractiveController as SiteInteractiveController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('main');
Route::get('set_lang/{lang}', [HomeController::class, 'setLang'])->name('set_lang');
Route::get('course/{course}', [SiteCourseController::class, 'show'])->name('course.show');
Route::get('buy/{course}', [BuyController::class, 'show'])->name('buy.show');
Route::get('admin', [AdminHomeController::class, 'index'])->name('admin');

Route::middleware(['verified'])->group(function () {
    // Роуты закрытые для неверифицированных
    Route::get('lesson/{lesson}', [SiteLessonController::class, 'show'])->name('lesson.show');
    Route::get('lesson/{lesson}/{user?}', [SiteLessonController::class, 'show'])->middleware('admin')->name('lesson.show');
    Route::post('interactive/{lesson}', [SiteInteractiveController::class, 'store'])->name('interactive.store');
    Route::post('interactive/{lesson}/{user?}', [SiteInteractiveController::class, 'store'])->middleware('admin')->name('interactive.store');
    Route::post('buy/{course}', [BuyController::class, 'store'])->name('buy.store');

    Route::middleware(['admin'])->prefix('admin')->group(function () {
        // Роуты открытые только для админа
        Route::get('/', [AdminHomeController::class, 'index'])->name('admin');
        Route::name('admin.')->group(function () {
            // Курсы
            Route::resource('course', CourseController::class);
            Route::resource('course/{course}/lesson', LessonController::class)->only(['create', 'store']);
            Route::get('course/{course}/restore', [CourseController::class, 'restore'])->name('course.restore');
            // Уроки
            Route::resource('lesson', LessonController::class)->only(['edit', 'update', 'destroy']);
            Route::get('lesson/{lesson}/restore', [LessonController::class, 'restore'])->name('lesson.restore');
            // Пользователи
            Route::resource('user', UserController::class)->only(['index', 'edit', 'update']);
            // Интерактив
            Route::get('interactive', [InteractiveController::class, 'index'])->name('interactive.index');
            Route::get('interactive/{lesson}', [InteractiveController::class, 'show'])->name('interactive.show');
            // Загрузчик изображений
            Route::post('image-uploader', [ImageController::class, 'upload'])->name('image-uploader');
        });
    });
});

require __DIR__.'/auth.php';

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

/**
 * Курсы
 *
 * @property int $id
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Carbon $deleted_at
 * @property string $name_ru
 * @property string $name_en
 * @property string $name_fr
 * @property float $price_rub
 * @property float $price_usd
 * @property float $price_eur
 */
class Course extends Model
{
    use HasFactory,
        SoftDeletes;

    protected $table = 'courses';

    protected $fillable = [
        'number',
        'name_ru',
        'name_en',
        'name_fr',
        'price_rub',
        'price_usd',
        'price_eur',
    ];

    protected $appends = [
        'name',
        'price',
        'poster',
    ];

    protected $withCount = [
        'lessons',
    ];

    public function getNameAttribute()
    {
        $localeName = 'name_' . app()->getLocale();

        return $this->$localeName;
    }

    public function getPriceAttribute()
    {
        $localePrice = 'price_' . config('app.currency.' . app()->getLocale());

        return $this->$localePrice;
    }

    public function getPosterAttribute()
    {
        $filePath = 'images/courses/' . $this->id . '.jpg';

        if (!Storage::exists($filePath)) {
            return null;
        }

        return $filePath . '?' . time();
    }

    /**
     * Уроки
     *
     * @return HasMany
     */
    public function lessons(): HasMany
    {
        return $this->hasMany(Lesson::class);
    }

    /**
     * Пользователи, оплатившие курс
     *
     * @return BelongsToMany
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CourseRequest;
use App\Models\Course;
use App\Services\CourseService;
use Artesaos\SEOTools\Facades\SEOMeta;

class CourseController extends Controller
{
    public function index()
    {
        SEOMeta::setTitle(__('Courses and lessons'));

        $courses = Course::withTrashed()->orderBy('number', 'asc')
            ->with(['lessons' => function ($builder) {
                $builder->withTrashed()->orderBy('number', 'asc');
            }])->paginate(config('app.per_page'));

        return view('admin/course/courses', [
            'courses' => $courses
        ]);
    }

    public function create()
    {
        SEOMeta::setTitle(__('Add course'));

        return view('admin.course/form');
    }

    public function store(CourseRequest $request, CourseService $courseService)
    {
        $courseService->create($request);

        return redirect()->route('admin.course.index')->withSuccess(__('Course created'));
    }

    public function edit($id)
    {
        SEOMeta::setTitle(__('Edit course'));

        $course = Course::withTrashed()->findOrFail($id);

        return view('admin.course/form', [
            'course' => $course,
        ]);
    }

    public function update(CourseRequest $request, $id, CourseService $courseService)
    {
        $course = Course::withTrashed()->findOrFail($id);

        $courseService->update($course, $request);

        return redirect()->route('admin.course.index')->withSuccess(__('Course successful updated'));
    }

    public function destroy($id, CourseService $courseService)
    {
        $course = Course::withTrashed()->findOrFail($id);

        $courseService->delete($course);

        session()->flash('success', __('Course deleted'));
    }

    public function restore($id, CourseService $courseService)
    {
        $course = Course::withTrashed()->findOrFail($id);

        $courseService->restore($course);

        return back()->withSuccess(__('Course restored'));
    }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use Artesaos\SEOTools\Facades\SEOMeta;

class CourseController extends Controller
{
    public function show(Course $course)
    {
        SEOMeta::setTitle($course->name);
        SEOMeta::setDescription($course->name . ': ' . $course->price);
        
        $course->load(['lessons' => function ($builder) {
            $builder->orderBy('number', 'asc');
        }]);

        return view('course', [
            'course' => $course
        ]);
    }
}

resources/views/admin/course/courses.blade.php
@extends('layouts/admin')

@section('content')
    <h1>@lang('Courses and lessons')</h1>

    <div class="btn-group form-group">
        <a class="btn btn-default" href="{{ route('admin.course.create') }}" role="button">
            @lang('Add course')
        </a>
    </div>

    @include('alert')

    @foreach ($courses as $course)
        
        <div class="panel panel-{{ $course->trashed() ? 'danger' : 'default' }}">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-9">
                        <h3 class="panel-title">{{ $course->number }}. {{ $course->name }}</h3>
                        <p class="help-block">@lang('Price'): {{ $course->price_rub }} rub / {{ $course->price_usd }} usd / {{ $course->price_eur }} eur</p>
                        <div class="btn-group">
                            <a class="btn btn-default" href="{{ route('admin.course.edit', $course) }}" role="button">@lang('Edit course')</a>
                            @if ($course->trashed())
                                <a class="btn btn-default" href="{{ route('admin.course.restore', $course) }}" role="button">@lang('Restore course')</a>
                            @else
                                <a class="btn btn-default" href="{{ route('admin.lesson.create', $course) }}" role="button">@lang('Add lesson')</a>
                            @endif
                            <a class="btn btn-danger" onclick="confirmDelete('{{ route('admin.course.destroy', $course) }}')" href="#" role="button">@lang('Delete course')</a>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        @if ($course->poster)
                            <img src="{{ $course->poster }}" alt="" class="img-responsive hidden-xs">
                        @endif
                    </div>
                </div>
            </div>

            @if ($course->lessons->isNotEmpty())
                  
                <div class="panel-body"> 
                    <h5>@lang('Lessons'):</h5>
                    <div class="table-responsive">
                        <table class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>@lang('Poster')</th>
                                    <th>@lang('Title')</th>
                                    <th>@lang('Control')</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($course->lessons as $lesson)
                                    <tr @if ($lesson->trashed()) class="danger" @endif>
                                        <td style="max-width: 120px;">
                                            @if ($lesson->poster)
                                                <img src="{{ $lesson->poster }}" alt="" class="img-responsive">
                                            @endif
                                        </td>
                                        <td>{{ $lesson->number }}. {{ $lesson->name }}</td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-default btn-sm" href="{{ route('admin.lesson.edit', $lesson) }}" role="button">@lang('Edit lesson')</a>
                                                @if ($lesson->trashed())
                                                    <a class="btn btn-default btn-sm" href="{{ route('admin.lesson.restore', $lesson) }}" role="button">@lang('Restore lesson')</a>
                                                @endif
                                                <a class="btn btn-danger btn-sm" onclick="confirmDelete('{{ route('admin.lesson.destroy', $lesson) }}')" href="#" role="button">@lang('Delete lesson')</a>
                                            </div>
                                            
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div> 
                    {{ $courses->links() }}
                </div>

            @endif

        </div>
    @endforeach
        
@endsection

resources/views/admin/course/form.blade.php
@extends('layouts/admin')

@section('content')
    <h1>@lang((isset($course) ? 'Edit' : 'Add') . ' course')</h1>

    @include('error')

    <form action="{{ isset($course) ? route('admin.course.update', $course) : route('admin.course.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        @if (isset($course))
            @method('PATCH')
        @endif


        <div role="tabpanel">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs nav-justified" role="tablist">
                <li role="presentation" class="active">
                    <a href="#ru" aria-controls="ru" role="tab" data-toggle="tab">@lang('ru')</a>
                </li>
                <li role="presentation">
                    <a href="#en" aria-controls="en" role="tab" data-toggle="tab">@lang('en')</a>
                </li>
                <li role="presentation">
                    <a href="#fr" aria-controls="fr" role="tab" data-toggle="tab">@lang('fr')</a>
                </li>
            </ul>
            <br>
            <div class="form-group">
                <label for="">@lang('Number')</label>
                <p class="help-block">@lang('This field is used to sort')</p>
                <input type="text" name="number" class="form-control" value="{{ old('number', $course->number ?? '') }}">
            </div>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="ru">
                    <div class="form-group">
                        <label for="name_ru">@lang('Title on russian')</label>
                        <input type="text" name="name_ru" class="form-control" value="{{ old('name_ru', $course->name_ru ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="price_rub">@lang('Price in rub')</label>
                        <input type="text" name="price_rub" class="form-control" value="{{ old('price_rub', $course->price_rub ?? '') }}">
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="en">
                    <div class="form-group">
                        <label for="name_en">@lang('Title on english')</label>
                        <input type="text" name="name_en" class="form-control" value="{{ old('name_en', $course->name_en ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="price_usd">@lang('Price in usd')</label>
                        <input type="text" name="price_usd" class="form-control" value="{{ old('price_usd', $course->price_usd ?? '') }}">
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="fr">
                    <div class="form-group">
                        <label for="name_fr">@lang('Title on french')</label>
                        <input type="text" name="name_fr" class="form-control" value="{{ old('name_fr', $course->name_fr ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="price_eur">@lang('Price in eur')</label>
                        <input type="text" name="price_eur" class="form-control" value="{{ old('price_eur', $course->price_eur ?? '') }}">
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="">@lang('Poster')</label>
            <span class="help-block">@lang('Left empty if you not want to change')</span>
            <input type="file" name="image" accept="image/*">
        </div>
        <div class="form-group">
            <input type="hidden" name="set_watermark" value="0">
            <label for="set_watermark">
                <input type="checkbox" checked name="set_watermark" id="set_watermark" value="1"> @lang('Set watermark on poster')
            </label>
        </div>
        <button type="submit" class="btn btn-primary">@lang('Save')</button>
    </form>

@endsection