routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\InteractiveController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\BuyController;
use App\Http\Controllers\CourseController as SiteCourseController;
use App\Http\Controllers\LessonController as SiteLessonController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InteractiveController as SiteInteractiveController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('main');
Route::get('set_lang/{lang}', [HomeController::class, 'setLang'])->name('set_lang');
Route::get('course/{course}', [SiteCourseController::class, 'show'])->name('course.show');
Route::get('buy/{course}', [BuyController::class, 'show'])->name('buy.show');
Route::get('admin', [AdminHomeController::class, 'index'])->name('admin');

Route::middleware(['verified'])->group(function () {
    // Роуты закрытые для неверифицированных
    Route::get('lesson/{lesson}', [SiteLessonController::class, 'show'])->name('lesson.show');
    Route::get('lesson/{lesson}/{user?}', [SiteLessonController::class, 'show'])->middleware('admin')->name('lesson.show');
    Route::post('interactive/{lesson}', [SiteInteractiveController::class, 'store'])->name('interactive.store');
    Route::post('interactive/{lesson}/{user?}', [SiteInteractiveController::class, 'store'])->middleware('admin')->name('interactive.store');
    Route::post('buy/{course}', [BuyController::class, 'store'])->name('buy.store');

    Route::middleware(['admin'])->prefix('admin')->group(function () {
        // Роуты открытые только для админа
        Route::get('/', [AdminHomeController::class, 'index'])->name('admin');
        Route::name('admin.')->group(function () {
            // Курсы
            Route::resource('course', CourseController::class);
            Route::resource('course/{course}/lesson', LessonController::class)->only(['create', 'store']);
            Route::get('course/{course}/restore', [CourseController::class, 'restore'])->name('course.restore');
            // Уроки
            Route::resource('lesson', LessonController::class)->only(['edit', 'update', 'destroy']);
            Route::get('lesson/{lesson}/restore', [LessonController::class, 'restore'])->name('lesson.restore');
            // Пользователи
            Route::resource('user', UserController::class)->only(['index', 'edit', 'update']);
            // Интерактив
            Route::get('interactive', [InteractiveController::class, 'index'])->name('interactive.index');
            Route::get('interactive/{lesson}', [InteractiveController::class, 'show'])->name('interactive.show');
            // Загрузчик изображений
            Route::post('image-uploader', [ImageController::class, 'upload'])->name('image-uploader');
        });
    });
});

require __DIR__.'/auth.php';

resources/views/layouts/admin.blade.php
@extends('layouts/app')

@section('page')
    <div class="row">
        <div class="col-md-3">
            
            <div class="btn-group-vertical btn-block">
                <a class="btn btn-default" href="{{ route('admin.course.index') }}" role="button">
                    @lang('Courses and lessons')
                </a>
                <a class="btn btn-default" href="{{ route('admin.user.index') }}" role="button">@lang('Students')</a>
                <a class="btn btn-default" href="{{ route('admin.interactive.index') }}" role="button">@lang('Interactive')</a>
            </div>
            
        </div>
        <div class="col-md-9">
            @yield('content')
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {!! SEOMeta::generate() !!}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.css" integrity="sha512-pDpLmYKym2pnF0DNYDKxRnOk1wkM9fISpSOjt8kWFKQeDmBTjSnBZhTd41tXwh8+bRMoSaFsRnznZUiH9i3pxA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="css/app.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="js/localization/{{ app()->getLocale() }}.js"></script>
    <script src="js/app.js?2"></script>

</head>
<body>

    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">@lang('Site name')</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">@lang('Language'): @lang(app()->getLocale()) <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ route('set_lang', 'ru') }}">@lang('ru')</a></li>
                        <li><a href="{{ route('set_lang', 'en') }}">@lang('en')</a></li>
                        <li><a href="{{ route('set_lang', 'fr') }}">@lang('fr')</a></li>
                    </ul>
                </li>
                @guest
                    <li><a href="{{ route('login') }}">@lang('Sign in')</a></li>
                    <li><a href="{{ route('register') }}">@lang('Sign up')</a></li>
                @else
                    @if (auth()->user()->is_admin)
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ auth()->user()->name }} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ route('admin') }}">@lang('Admin panel')</a></li>
                            </ul>
                        </li>
                    @else
                        <li>
                            <p class="navbar-text">{{ auth()->user()->name }}</p>
                        </li>
                    @endif
                    <li>
                        <a href="#" onclick="event.preventDefault();
                        document.getElementById('logout_form').submit();">@lang('Logout')</a>
                        <form method="POST" action="{{ route('logout') }}" id="logout_form">
                            @csrf
                        </form>
                    </li>
                @endguest
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>

    <div class="container">

        @if (auth()->check() && !(bool) auth()->user()->email_verified_at)
            <div class="alert alert-warning">
                @lang('Confirm your email to open all the functions of the site')
            </div>
        @endif

        @if ($pageinfo = session('pageinfo'))
            <div class="alert alert-info">{{ $pageinfo }}</div>
        @endif

        @yield('page')
        <br>
        <br>
    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
@extends('layouts/app')

@section('page')
    {{ $slot }}
@endsection