routes/web.php
<?php

use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\ImageController;
use App\Http\Controllers\Admin\InteractiveController;
use App\Http\Controllers\Admin\LessonController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\BuyController;
use App\Http\Controllers\CourseController as SiteCourseController;
use App\Http\Controllers\LessonController as SiteLessonController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InteractiveController as SiteInteractiveController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('main');
Route::get('set_lang/{lang}', [HomeController::class, 'setLang'])->name('set_lang');
Route::get('course/{course}', [SiteCourseController::class, 'show'])->name('course.show');
Route::get('buy/{course}', [BuyController::class, 'show'])->name('buy.show');
Route::get('admin', [AdminHomeController::class, 'index'])->name('admin');

Route::middleware(['verified'])->group(function () {
    // Роуты закрытые для неверифицированных
    Route::get('lesson/{lesson}', [SiteLessonController::class, 'show'])->name('lesson.show');
    Route::get('lesson/{lesson}/{user?}', [SiteLessonController::class, 'show'])->middleware('admin')->name('lesson.show');
    Route::post('interactive/{lesson}', [SiteInteractiveController::class, 'store'])->name('interactive.store');
    Route::post('interactive/{lesson}/{user?}', [SiteInteractiveController::class, 'store'])->middleware('admin')->name('interactive.store');
    Route::post('buy/{course}', [BuyController::class, 'store'])->name('buy.store');

    Route::middleware(['admin'])->prefix('admin')->group(function () {
        // Роуты открытые только для админа
        Route::get('/', [AdminHomeController::class, 'index'])->name('admin');
        Route::name('admin.')->group(function () {
            // Курсы
            Route::resource('course', CourseController::class);
            Route::resource('course/{course}/lesson', LessonController::class)->only(['create', 'store']);
            Route::get('course/{course}/restore', [CourseController::class, 'restore'])->name('course.restore');
            // Уроки
            Route::resource('lesson', LessonController::class)->only(['edit', 'update', 'destroy']);
            Route::get('lesson/{lesson}/restore', [LessonController::class, 'restore'])->name('lesson.restore');
            // Пользователи
            Route::resource('user', UserController::class)->only(['index', 'edit', 'update']);
            // Интерактив
            Route::get('interactive', [InteractiveController::class, 'index'])->name('interactive.index');
            Route::get('interactive/{lesson}', [InteractiveController::class, 'show'])->name('interactive.show');
            // Загрузчик изображений
            Route::post('image-uploader', [ImageController::class, 'upload'])->name('image-uploader');
        });
    });
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Course;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'locale',
        'name',
        'login',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = [
        'is_admin',
    ];

    /**
     * Администратор или нет
     *
     * @return boolean
     */
    public function getIsAdminAttribute(): bool
    {
        return in_array($this->id, config('app.admin_user_ids', []));
    }

    /**
     * Выборка "Ученики"
     *
     * @param Builder $builder
     * @return void
     */
    public function scopeStudent(Builder $builder)
    {
        return $builder->whereNotIn('id', config('app.admin_user_ids', []));
    }

    /**
     * Курсы пользователя
     *
     * @return BelongsToMany
     */
    public function courses(): BelongsToMany
    {
        return $this->belongsToMany(Course::class);
    }

    /**
     * Сообщения интерактива
     *
     * @return HasMany
     */
    public function interactives(): HasMany
    {
        return $this->hasMany(Interactive::class, 'user_id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\User;
use App\Services\UserService;
use Artesaos\SEOTools\Facades\SEOMeta;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function index()
    {
        SEOMeta::setTitle(__('Students'));

        $users = User::student()->withCount('courses')->paginate(config('app.per_page'));

        return view('admin/user/users', [
            'users' => $users
        ]);
    }

    public function edit(User $user)
    {
        SEOMeta::setTitle(__('Purchased courses for') . ': ' . $user->name);

        $courses = Course::all();

        $user->load('courses');

        return view('admin/user/form', [
            'user' => $user,
            'courses' => $courses,
        ]);
    }

    public function update(User $user, Request $request, UserService $userService)
    {
        $userService->update($user, $request);

        return redirect()->route('admin.user.index')->withSuccess(__('Student access to courses updated'));
    }
}

resources/views/admin/user/form.blade.php
@extends('layouts/admin')

@section('content')
    <h1>@lang('Purchased courses for'): {{ $user->name }}</h1>
    
    <form action="{{ route('admin.user.update', $user) }}" method="POST">
        @csrf
        @method('PATCH')
        
        @foreach ($courses as $course)
            <div class="checkbox">
                <label>
                    <input name="courses[]" @if ($user->courses->contains($course->id)) checked @endif type="checkbox" value="{{ $course->id }}">
                    {{ $course->name }}
                </label>
            </div>
        @endforeach
        
        <button type="submit" class="btn btn-primary">@lang('Save')</button>
    </form>
    
@endsection

resources/views/admin/user/users.blade.php
@extends('layouts/admin')

@section('content')
    <h1>@lang('Students')</h1>

    @include('alert')

    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>@lang('Name')</th>
                    <th>@lang('Courses count')</th>
                    <th>@lang('Control')</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
        
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->courses_count }}</td>
                        <td>
                            <a href="{{ route('admin.user.edit', $user) }}" class="btn btn-default btn-sm">
                                @lang('More')
                            </a>
                        </td>
                    </tr>

                @endforeach
            </tbody>
        </table>
    </div>
    
    {{ $users->links() }}
    
        
@endsection